FROM eclipse-temurin:17-jdk-alpine

# Set working directory
WORKDIR /app

# Update system and set timezone to Asia/Kuala_Lumpur
RUN apk update && apk add tzdata curl && cp /usr/share/zoneinfo/Asia/Kuala_Lumpur /etc/localtime && apk del tzdata

# Copy built JAR into container
COPY target/library-system.jar library-system.jar

# Run application
ENTRYPOINT ["java","-Dspring.profiles.active=dev","-jar","/app/library-system.jar"]

# Expose port 8080
EXPOSE 8080