spring:
  datasource:
    url: jdbc:h2:mem:aeonbank;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    driverClassName: org.h2.Driver
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  sql:
    init:
      mode: 'always'
  h2:
    console:
      enabled: true
springdoc:
  api-docs:
    enabled: false
  swagger-ui:
    enabled: false