---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: library-system
  namespace: prod
spec:
  replicas: 1
  selector:
    matchLabels:
      app: library-system
  strategy:
    type: RollingUpdate
    rollingUpdate: 
      maxUnavailable: 0
      maxSurge: 2
  template:
    metadata:
      labels:
        app: library-system
    spec:
      containers:
      - name: library-system
        image: "$IMAGE"
        ports:
        - containerPort: 8080
        readinessProbe:
          httpGet:
            port: 8080
            path: /library-system/actuator/health
          # Delay before the first probe (equal to your startup time)
          initialDelaySeconds: 3
          # Maximum time to wait for a response
          timeoutSeconds: 2
          # How often to perform the probe
          periodSeconds: 10
          # How many consecutive failures are allowed before considering it not ready
          failureThreshold: 30
        resources:
          limits:
            memory: 512Mi
          requests:
            cpu: 300m
            memory: 512Mi
        env:
        - name: ECR_REPO_URL
          valueFrom:
            secretKeyRef:
              name: ecr-repo-secret  # Kubernetes Secret reference
              key: ECR_URL
