---
apiVersion: v1
kind: Service
metadata:
  name: library-system
  namespace: staging
  labels:
    app: library-system
    spring-boot: "true"
spec:
  ports:
  - port: 8080
  selector:
    app: library-system